### ISSUE TITLE
Log card history

### ISSUE THREAD

**Issue by bkutil** [cthiel/cardboard#48]
Ability to see the action history, .i.e. seeing in what deck the card has been a week before (or whatever the sprint duration is). Use case would be using the cards to track progress and generate status updates.

**Comment by cthiel** [comment]
The backend already supports this, as we are keeping every version of cards + decks using the paper_trail gem. We just need to make it visible in the UI. Garrett, do you have an idea for this?

**Comment by garrett** [comment]
Perhaps we should have a timeline mode, like Etherpad.

It would allow you to rollback to various states, but only as read-only. 

(From there, if one wanted to _really_ rollback, they could then blast away the current state with the old one. It's questionable, however... I think it would simply copy & overwrite the state, preserving history. That is, _if_ we decide that this would actually be a feature.)

Also: The way I'm imagining timeline mode is that a timeline slider widget actually slides in from the top of the page instead of going to a different UI.

**Comment by bkutil** [comment]
Imho it's not important for the history to be 'rewritable', only to be able to 'view' or access the state in a previous point in time, so you can easily see the what the item state was back then.The timeline slider would make sense, with the item in previous time being opaque and not editable?

**Comment by garrett** [comment]
Yeah, the rewritable history was just a related thought. I'm not so sure about having it, hence the _if_.  (:

It should be enough to just browse the history. (I don't think people will need to "check out" older versions for their current history, in other words.)

Right, I think a read-only timeline approach is what's right for this.
