### ISSUE TITLE
Plaintext export

### ISSUE THREAD

**Issue by bkutil** [cthiel/cardboard#49]
It would be nice to be able to export the board in plain text format, like:

Date of the export.

State1
  -> Card title
       Card description
State2
  -> Card title
       Card description
...

Again, use case is generating reports from the board.

**Comment by garrett** [comment]
We pretty much have the data almost like that already, if you remove most of the CSS. Try printing (to a PDF) to see what I mean.

(That is, unless this has changed. Last I checked, it mostly worked. We'll want proper print support, with a real print.css. See issue #36 for print support.)

For strictly plain text output, we should be able to easily do this, especially since the text is written in markdown already. Basically, we'd just make everything exported as plain text markdown (with headers being markdown-style), and include the plain text of the content.
